name: playstore
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0-323.2.beta

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/WhatsApp Image 2024-10-08 at 22.21.00_2ca774dc.jpg
    - assets/4.jpg
    - assets/1.jpg
    - assets/2.jpg
    - assets/3.jpg
    - assets/D.jpg
    - assets/5.jpg


